name: Deploy

on:
  workflow_run:
    workflows: ["Build & deploy docker image CI"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-www1:
    runs-on: ubuntu-latest
    environment: www1
    steps:
      - uses: actions/checkout@v2

      - name: ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: 'docker-compose -f /var/www/vospel.cz/docker-compose.yml pull && docker-compose -f /var/www/vospel.cz/docker-compose.yml down && docker-compose -f /var/www/vospel.cz/docker-compose.yml up -d'
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          privatekey: ${{ secrets.SSH_KEY }}
      
