name: push

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: pnpm/action-setup@v2
     - uses: actions/setup-node@v3
       with:
         node-version: 18
         cache: pnpm

     - name: Install
       run: pnpm i

     - name: Lint
       run: pnpm lint
   
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/marekvospel/vospel.cz:latest